version: 0.2
phases:
  install:
    commands:
      - npm cache clean
      - npm install
  pre_build:
    commands:
      - npm run test
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run package
artifacts:
  type: zip
  files:
    - packaged.sam.yaml
    - dist/*

