AWSTemplateFormatVersion: 2010-09-09
Description: dotlabs-proxy-app
Transform:
- AWS::Serverless-2016-10-31
Parameters:
  authToken:
    Description: Token for usage
    Type: String
  userAgent:
    Description: Name of the user agent
    Type: String
    Default: dotlabs-proxy
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        AUTH_TOKEN:
          Ref: authToken
        USER_AGENT:
          Ref: userAgent
Resources:
  searcFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dotlabs-proxy-bucket/0b1079341094771f1c4fe971a83645d0
      Handler: index.searchHandler
      Description: Search proxy handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
