AWSTemplateFormatVersion: 2010-09-09
Description: dotlabs-proxy-app
Transform:
- AWS::Serverless-2016-10-31
Parameters:
  authToken:
    Description: Token for usage
    Type: String
  userAgent:
    Description: Name of the user agent
    Type: String
    Default: 'dotlabs-proxy'
Globals:
  Api:
    # enable CORS;
    Cors:
      AllowHeaders: "'Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization'"
      AllowOrigin: "'*'"
  Function:
    Runtime: nodejs12.x
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        AUTH_TOKEN: !Ref authToken
        USER_AGENT: !Ref userAgent

Resources:
  DotlabsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  searcFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: './dist'
      Handler: 'index.searchHandler'
      Description: Search proxy handler
      Events:
        Search:
          Type: Api
          Properties:
            Path: /v1/github-service/search
            Method: GET
            RestApiId: !Ref DotlabsApi

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${DotlabsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
