export const searchResultExample = {
    "login": "gozmozdony",
    "id": 5528598,
    "node_id": "MDQ6VXNlcjU1Mjg1OTg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5528598?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gozmozdony",
    "html_url": "https://github.com/gozmozdony",
    "followers_url": "https://api.github.com/users/gozmozdony/followers",
    "following_url": "https://api.github.com/users/gozmozdony/following{/other_user}",
    "gists_url": "https://api.github.com/users/gozmozdony/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gozmozdony/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gozmozdony/subscriptions",
    "organizations_url": "https://api.github.com/users/gozmozdony/orgs",
    "repos_url": "https://api.github.com/users/gozmozdony/repos",
    "events_url": "https://api.github.com/users/gozmozdony/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gozmozdony/received_events",
    "type": "User",
    "site_admin": false,
    "score": 1.0
};
