export const searchResultExample = {
    "login": "gozmozdony",
    "id": 5528598,
    "node_id": "MDQ6VXNlcjU1Mjg1OTg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5528598?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gozmozdony",
    "html_url": "https://github.com/gozmozdony",
    "followers_url": "https://api.github.com/users/gozmozdony/followers",
    "following_url": "https://api.github.com/users/gozmozdony/following{/other_user}",
    "gists_url": "https://api.github.com/users/gozmozdony/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gozmozdony/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gozmozdony/subscriptions",
    "organizations_url": "https://api.github.com/users/gozmozdony/orgs",
    "repos_url": "https://api.github.com/users/gozmozdony/repos",
    "events_url": "https://api.github.com/users/gozmozdony/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gozmozdony/received_events",
    "type": "User",
    "site_admin": false,
    "score": 1.0
};

export const userResultExample = {
    "login": "octocat",
    "id": 1,
    "node_id": "MDQ6VXNlcjE=",
    "avatar_url": "https://github.com/images/error/octocat_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/octocat",
    "html_url": "https://github.com/octocat",
    "followers_url": "https://api.github.com/users/octocat/followers",
    "following_url": "https://api.github.com/users/octocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
    "organizations_url": "https://api.github.com/users/octocat/orgs",
    "repos_url": "https://api.github.com/users/octocat/repos",
    "events_url": "https://api.github.com/users/octocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/octocat/received_events",
    "type": "User",
    "site_admin": false,
    "name": "monalisa octocat",
    "company": "GitHub",
    "blog": "https://github.com/blog",
    "location": "San Francisco",
    "email": "octocat@github.com",
    "hireable": false,
    "bio": "There once was...",
    "twitter_username": "monatheoctocat",
    "public_repos": 2,
    "public_gists": 1,
    "followers": 20,
    "following": 0,
    "created_at": "2008-01-14T04:33:35Z",
    "updated_at": "2008-01-14T04:33:35Z"
};
